image: docker:18.02.0-git

before_script:
  - chmod +x ./linux/*.sh

stages:
  - Build
  - production

build-joona-frontend-image:
  stage: Build
  script:
    - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
    - docker build -t jaska/joona-frontend:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA -f dockerfiles/frontend/Dockerfile .
    - docker push jaska/joona-frontend

build-joona-api-image:
  stage: Build
  script:
    - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
    - docker build -t jaska/joona-api:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA -f dockerfiles/api/Dockerfile .
    - docker push jaska/joona-api

deploy-production:
  stage: production
  script:
    - ./linux/install_dependencies.sh
    - ./linux/setup_kubectl.sh
    - ./linux/install_tiller.sh
    - ./linux/helm_upgrade.sh