language: node_js
node_js:
  "7"
install:
  npm install

script:
  - npm run build-production
  - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
  - docker build -t $DOCKER_ID_USER/joona .
  - docker push $DOCKER_ID_USER/joona
notifications:
  webhooks: http://salainen_kontti_updater.ths.tunk.org/