apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-joona-frontend
  labels:
    app: {{ .Release.Name }}-joona-frontend
spec:
  template:
    metadata:
      labels:
        app: joona-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.joonaFrontendImage }}"
          ports:
            - containerPort: 80