apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: joona
  labels:
    app: joona
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: joona
    spec:
      containers:
        - name: joona-container
          image: "{{ .Values.joonaImage }}"
          ports:
            - containerPort: 80