apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: joona
  labels:
    app: joona
spec:
  template:
    metadata:
      labels:
        app: joona
    spec:
      containers:
        - name: joona-container
          image: "{{ .Values.joonaImage }}"
          ports:
            - containerPort: 80